--------------------------------------------------------------------------------------------------------------------------------------
----- MONTO ADSL
SELECT DIF, SUM(MONTO) FROM (
SELECT DIF, PRECIO, BAR_UNI, PRECIO*BAR_UNI AS MONTO FROM DATA1908 WHERE DIF IN ('AVERIAS ASDL', 'AVERIAS STB') AND PRECIO IS NOT NULL AND DIF = 'AVERIAS ASDL') A
GROUP BY DIF


SELECT PRECIO, DIF, CZONAL, CONTRA FROM DATA1908 WHERE CZONAL = 'LIM'
21314
----- MONTO STB
SELECT DIF, SUM(MONTO) FROM (
SELECT DIF, PRECIO, BAR_UNI, PRECIO*BAR_UNI AS MONTO FROM DATA1908 WHERE DIF IN ('AVERIAS ASDL', 'AVERIAS STB') AND PRECIO IS NOT NULL AND DIF = 'AVERIAS STB') A
GROUP BY DIF

23698 / 768061
SELECT * FROM PRECIO_NUEVO
SELECT * FROM PRECIOS
23698 / 646511
---------------------------------MONTOS----------------------------------------------------------------------
SELECT CONTRA, DIF, ROUND(SUM((CASE WHEN CZONAL = 'LIMA' THEN 28.5 ELSE 27.37 END)*BAR_UNI),2) FROM DATA1908 GROUP BY CONTRA, DIF HAVING CONTRA IS NOT NULL

SELECT CONTRA,DIF, SUBSTRING(IND_PAQ,1,3) AS 'CAT',ROUND(SUM(PRECIO*BAR_UNI),2)
SELECT DISTINCT CZONAL,PRECIO FROM
DATA1908 WHERE
CONTRA='COBRA' AND
SUBSTRING(IND_PAQ,1,3) ='SAW'
GROUP BY
CONTRA,DIF, SUBSTRING(IND_PAQ,1,3)


SELECT DIF, PRECIO, CONTRA, ZONAL FROM DATA1908 WHERE PRECIO IS NULL


SELECT CONTRA, DIF, ROUND(SUM(MONTO),2) FROM DATA1908 GROUP BY CONTRA, DIF HAVING CONTRA IS NOT NULL

SELECT CONTRATA, CTECNICO FROM ADSL_FINAL WHERE CONTRATA IS NULL
