--TABLAS ORIGEN
SELECT * FROM ADSL
SELECT * FROM STB
--TABLAS CALCULADAS

-- OTRAS TABLAS


-- Archivo ADSL
SELECT A,ZON,C_CIUDAD,MDF,AVERIA,CODSEG,inscripcio, CODEECC,CODLIQ,DDESCODLIQ,CODDETLIQ,DESCODDET,DGRUPO,ESTALIQ,OBSESTLIQ,DISTRITO,
FECHA_ADSL,FECHA_REG,FECHA_LIQU,MM_LIQ,AA_LIQ,JEF_CMR,USUALIQ,DTSERV,CODMOD,DESMODA,CTECNICO,SEG_OPE INTO ADSL FROM INDICA_ADSL_PAIS


--Archivo STB
SELECT cod_unico, Zonal,Distrito, Codseg, Mdf, Ti_liqn, Ti_liqn_de, Duracion, Mm_liq, Aa_liq, Gerencia, Jef_CMR, Eecc, Fecha_repo,
Fecha_liqu, Co_area_si, Co_usua_li, Fecha_alta  INTO STB FROM INDICA_STB_PAIS

--Archivo RCOBRE

SELECT * INTO RCOBRE_ADSL FROM REIT_SE
WHERE RE_FE_LIQU is not null and  TI_LIQN is not null and (DBO.TRIM(NEGOCIO)='STB' or DBO.TRIM(NEGOCIO)='ADSL')

SELECT * INTO RCOBRE_STB FROM REIT_SE
WHERE RE_FE_LIQU is not null and  TI_LIQN is not null and (DBO.TRIM(NEGOCIO)='STB' or DBO.TRIM(NEGOCIO)='ADSL')


-- Archivo ICOBRE

/*Consulta para crear la tabla ICOBRE*/
--declare @mes int =9;
SELECT *INTO ICOBRE FROM DET_ALTAS
WHERE MONTH(fejepex)= 9  AND TI_LIQN is not null and (NEGOCIO='STB' or NEGOCIO='ADSL')


--******************************************************************************************

--GLORIA
/*
ADSL_FINAL=23698,
STB_FINAL=21314,
REIT_ADSL=4729,
REIT_STB=2946
*/

--AP
/* 23/10/2019
ADSL_FINAL=23482,
STB_FINAL=21307,
REIT_ADSL=5387,
REIT_STB=3313
*/

--AP
/* 29/10/2019
ADSL_FINAL=23499,
STB_FINAL=21311,
REIT_ADSL=5390,
REIT_STB=3314
*/


SELECT COUNT(*) FILAS_ADSL_FINAL FROM ADSL_FINAL
SELECT COUNT(*) FILAS_STB_FINAL FROM STB_FINAL;
SELECT COUNT(*) FILAS_REIT_ADSL FROM REIT_ADSL;
SELECT COUNT(*) FILAS_REIT_STB FROM REIT_STB;

SELECT * FROM ADSL_FINAL
SELECT * FROM STB_FINAL
SELECT * FROM REIT_ADSL
