


--*******************************************************************
	-- CARGA_AVERIAS_DUO_A_DATA

 TRUNCATE TABLE DATA1908

 ALTER TABLE ADSL_FINAL ADD CONTRATA NVARCHAR(255)
 ALTER TABLE STB_FINAL ADD CONTRATA NVARCHAR(255)
 ALTER TABLE STB_FINAL ALTER COLUMN TI_LIQN_DE NVARCHAR(255)
 ALTER TABLE REIT_ADSL ALTER COLUMN CODAVERIA NVARCHAR(255)
 ALTER TABLE REIT_STB ALTER COLUMN CODAVERIA NVARCHAR(255)

 -- 94 FILAS NO TIENEN CONTRATA --> ADSL_FINAL
-- SELECT CTECNICO, CONTRATA FROM ADSL_FINAL WHERE CONTRATA IS NULL

UPDATE ADSL_FINAL
SET CONTRATA = 'COBRA'
WHERE SUBSTRING(CTECNICO,1,2) = 'AB'

GO

UPDATE ADSL_FINAL
SET CONTRATA = 'LARI'
WHERE SUBSTRING(CTECNICO,1,2) = 'LA'

GO

UPDATE ADSL_FINAL
SET CONTRATA = 'DOMINION'
WHERE SUBSTRING(CTECNICO,1,2) = 'DO'

GO

UPDATE ADSL_FINAL
SET CONTRATA = 'CALATEL'
WHERE SUBSTRING(CTECNICO,1,2) = 'CA'

GO

UPDATE ADSL_FINAL
SET A = 'P'
WHERE MDF IN ('HUAL', 'CHAN')

GO

UPDATE ADSL_FINAL
SET ZON = 'CHB'
WHERE MDF IN ('HUAL', 'CHAN')

GO

--------------------------------------------------------
/*
SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS' --WCECO
SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS' --COD_CUENTA
SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS' --WAF
SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS' --DESCTA¨
*/

UPDATE ADSL_FINAL
SET ZON = 'PRO'
WHERE A = 'P'


GO

UPDATE ADSL_FINAL
SET ZON = 'LIM'
WHERE A = 'L'

GO

/* ESTA COMENTADO PORQUE LOS QUERYS ESTAN EN LA ULTIMA PARTE DEL ARCHIVO

-- UNIDADES

UPDATE A
SET A.DESC_UNI = B.DESC_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0'


-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
-- PRECIOS

UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO,
A.OPEX = A.BAR_TOT*A.PRECIO
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'AVERIAS ADSL'

GO

-- JEFATURAS_REGIONES

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
*/

-- 208 FILAS NO TIENEN CONTRATA --> STB_FINAL
-- SELECT EECC, CONTRATA FROM STB_FINAL WHERE CONTRATA IS NULL

UPDATE STB_FINAL
SET CONTRATA = 'COBRA'
WHERE DBO.TRIM(EECC) = 'AB'

GO

UPDATE STB_FINAL
SET CONTRATA = 'LARI'
WHERE DBO.TRIM(EECC) = 'LA'

GO

UPDATE STB_FINAL
SET CONTRATA = 'DOMINION'
WHERE DBO.TRIM(EECC) = 'DO'

GO

UPDATE STB_FINAL
SET CONTRATA = 'CALATEL'
WHERE DBO.TRIM(EECC) = 'CA'

GO

UPDATE STB_FINAL
SET ZONAL = 'LIM'
WHERE ZONAL = 'LIMA'

GO

UPDATE STB_FINAL
SET ZONAL = 'PRO'
WHERE ZONAL <> 'LIM'

GO
----------------------------------------------------------------------------------------------

/* ESTA COMENTADO PORQUE LOS QUERYS ESTAN EN LA ULTIMA PARTE DEL ARCHIVO
--STB_FINAL

--UNIDADES

UPDATE A
SET A.DESC_UNI = B.DESC_UNI,
	A.COD_UNI = B.COD_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72300-2'

GO

-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
-- PRECIOS

UPDATE A
SET A.PRECIO = B.PRECIO,
	A.MONTO = A.BAR_TOT*A.PRECIO,
	A.OPEX = A.BAR_TOT*A.PRECIO
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'AVERIAS STB'

/*
ALTER TABLE STB_FINAL ADD PRECIO FLOAT;
ALTER TABLE STB_FINAL ADD MONTO FLOAT;
ALTER TABLE STB_FINAL ADD OPEX FLOAT;
*/

-- JEFATURAS REGIONES

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
*/



-- ALTER TABLE STB_FINAL ALTER COLUMN TI_LIQN_DE NVARCHAR(255)

-- ******************************************************************
-- ******************************************************************



/*
ALTER TABLE DATA1908 ALTER COLUMN FECEJE NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN DESCRIPT NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN MOV NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN PLAYA NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN N_NEGOCIO NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN NEG_NUE NVARCHAR(255)
*/



--**************************************************************************************MES 09 NO HAY INFANCIAS
-- CARGA_INFANCIAS_DUO_A_DATA

/*
UPDATE INF_ADSL
SET CONTRATA = 'COBRA'
WHERE SUBSTRING(CODCIP,1,2) = 'AB'

GO

UPDATE INF_ADSL
SET CONTRATA = 'LARI'
WHERE SUBSTRING(CODCIP,1,2) = 'LA'

GO

UPDATE INF_ADSL
SET CONTRATA = 'DOMINION'
WHERE SUBSTRING(CODCIP,1,2) = 'DO'

GO

UPDATE INF_ADSL
SET CONTRATA = 'CALATEL'
WHERE SUBSTRING(CODCIP,1,2) = 'CA'

GO

UPDATE INF_ADSL
SET AREA = 'P'
WHERE CMDF IN ('HUAL', 'CHAN')

GO

UPDATE INF_ADSL
SET ZON = 'CHB'
WHERE CMDF IN ('HUAL', 'CHAN')

GO
--------------------------------------------------------

UPDATE INF_ADSL
SET ZON = 'PRO'
WHERE AREA = 'P'

GO

UPDATE INF_ADSL
SET ZON = 'LIM'
WHERE AREA = 'L'

GO

-- CUANDO EN EL SEEK ES UN VALOR UTILIZAR UN UPDATE-JOIN CON WHERE = VALOR

-- BAREMO TOTAL *0.75
/*
UPDATE A
SET A.DESC_UNI = 'INFANCIA -75%',
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0'
*/



/*
UPDATE A
SET A.PRECIO = B.PRECIO,
	A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
	A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
*/



/*
UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
*/

--*************************************************************************************
--*************************************************************************************

UPDATE INF_STB
SET CONTRATA = 'COBRA'
WHERE SUBSTRING(DBO.TRIM(CODCIP),1,2) = 'AB'



UPDATE INF_STB
SET CONTRATA = 'LARI'
WHERE SUBSTRING(DBO.TRIM(CODCIP),1,2) = 'LA'



UPDATE INF_STB
SET CONTRATA = 'DOMINION'
WHERE SUBSTRING(DBO.TRIM(CODCIP),1,2) = 'DO'



UPDATE INF_STB
SET CONTRATA = 'CALATEL'
WHERE SUBSTRING(DBO.TRIM(CODCIP),1,2) = 'CA'



UPDATE INF_STB
SET AREA = 'P'
WHERE CMDF IN ('HUAL', 'CHAN')



UPDATE INF_STB
SET ZON = 'CHB'
WHERE CMDF IN ('HUAL', 'CHAN')

*/



-- CUANDO EN EL SEEK ES UN VALOR UTILIZAR UN UPDATE-JOIN CON WHERE = VALOR
-- Poner el baremo al 75%

/*
UPDATE A
SET A.DESC_UNI = 'INFANCIA -75%',
	A.COD_UNI = B.COD_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0'
*/



-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
/*
UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
*/



/*
UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF AND A.ZONAL = B.ZONAL
*/



--*************************************************************************************
--*************************************************************************************
/*
ALTER DATABASE PV_STC_COMISIONES SET RECOVERY SIMPLE



DBCC SHRINKFILE (PV_STC_COMISIONES, 5)



ALTER DATABASE PV_STC_COMISIONES SET RECOVERY FULL


*/

--*********************************************************************************************
-- CARGA_REITERADAS_DUO_A_DATA
-- DATA1909
-- ALTER TABLE REIT_ADSL ADD CONTRATA NVARCHAR(255)

-- 54 FILAS SIN CONTRATA
-- SELECT CONTRA_TEC, CONTRATA FROM REIT_ADSL WHERE CONTRATA IS NULL

UPDATE REIT_ADSL
SET CONTRATA = 'COBRA'
WHERE CONTRA_TEC = 'AB'

GO

UPDATE REIT_ADSL
SET CONTRATA = 'LARI'
WHERE CONTRA_TEC = 'LA'

GO

UPDATE REIT_ADSL
SET CONTRATA = 'DOMINION'
WHERE CONTRA_TEC = 'DO'

GO

UPDATE REIT_ADSL
SET CONTRATA = 'CALATEL'
WHERE CONTRA_TEC = 'CA'

GO


UPDATE REIT_ADSL
SET AREA = 'P'
WHERE CO_MDF IN ('HUAL', 'CHAN')

GO

UPDATE REIT_ADSL
SET ZON = 'CHB'
WHERE CO_MDF IN ('HUAL', 'CHAN')

GO

UPDATE REIT_ADSL
SET ZON = 'PRO'
WHERE AREA = 'P'

GO

UPDATE REIT_ADSL
SET ZON = 'LIM'
WHERE AREA = 'L'

GO


/* ESTA COMENTADO PORQUE ESTAS QUERYS ESTAS MAS ABAJO
-- REIT_ADSL
--UNIDADES

UPDATE A
SET A.COD_UNI = B.COD_UNI,
	A.DESC_UNI = 'REITERADA -75%',
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0' AND DIF = 'REITERADAS STB'

-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE


UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'REITERADAS STB'

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
*/



-- ALTER TABLE REIT_ADSL ALTER COLUMN CODAVERIA NVARCHAR(255)

--***********************************************************************************
--***********************************************************************************





-- ALTER TABLE REIT_STB ADD CONTRATA NVARCHAR(255)

-- 26 FILAS NO TIENEN CONTRATA REIT_STB
-- SELECT CONTRA_TEC, CONTRATA FROM REIT_STB WHERE CONTRATA IS NULL

UPDATE REIT_STB
SET CONTRATA = 'COBRA'
WHERE DBO.TRIM(CONTRA_TEC) = 'AB'

GO

UPDATE REIT_STB
SET CONTRATA = 'LARI'
WHERE DBO.TRIM(CONTRA_TEC) = 'LA'

GO

UPDATE REIT_STB
SET CONTRATA = 'DOMINION'
WHERE DBO.TRIM(CONTRA_TEC) = 'DO'

GO

UPDATE REIT_STB
SET CONTRATA = 'CALATEL'
WHERE DBO.TRIM(CONTRA_TEC) = 'CA'

GO

UPDATE REIT_STB
SET AREA = 'P'
WHERE CO_MDF IN ('HUAL', 'CHAN')

GO

UPDATE REIT_STB
SET ZON = 'CHB'
WHERE CO_MDF IN ('HUAL', 'CHAN')

GO

UPDATE REIT_STB
SET ZON = 'LIM'
WHERE AREA = 'L'

UPDATE REIT_STB
SET ZON = 'PRO'
WHERE AREA = 'P'


-- CUANDO EN EL SEEK ES UN VALOR UTILIZAR UN UPDATE-JOIN CON WHERE = VALOR


/* ESTA COMENTADO PORQUE ESTAS QUERYS ESTAS MAS ABAJO
-- REIT_STB
-- UNIDADES

UPDATE A
SET A.DESC_UNI = 'REITERADA -75%',
	A.COD_UNI = B.COD_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0' AND DIF = 'REITERADAS STB'


-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
--PRECIOS

UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'REITERADAS STB'

--JEFATURAS_REGIONES

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF AND A.ZONAL = B.ZONAL
*/



-- ******************************************************************************
-- ******************************************************************************

INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,	TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,	CONTRA ,	ORDEN_OT ,
RUTAC ,	CODREQ ,	CZONAL, ZONAL ,	CMDF_NODO ,	--MOV_MAT
INS_CODCLI ,	TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,	DESCRIPT ,	MOV ,	PLAYA ,	N_NEGOCIO ,	NEG_NUE ,	ACT_MAT ,	MOV_MAT ,
ACTIVIDAD ,	TELEFONO ,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,	IND_PAQ ,	CANT, DIF)
SELECT  (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),	 'BUCLE',	 'OPEX',	 'TDP',	 CODEECC,
CONTRATA,	 SUBSTRING(AVERIA,4,7),	 0,	 0,	 ZON, ZON,	 MDF	-- 'AVERIAS'
, 0,	 ' ',	 ' ',	 ' ',   FECHA_LIQU,	 DBO.TRIM(codliq)+'-'+DBO.TRIM(coddetliq)+'-'+DBO.TRIM(ddescodliq),	 'AVERIAS',	 0,	 'SPEEDY',
'AVERIAS ADSL',	 'BA',	 'AVERIAS',	 'AVERIAS ADSL',	 0,	 ' ',	 ' ',	 ' ',	 ' ',	 DESMODA,	 AVERIA,	 1, 'AVERIAS ADSL'
FROM ADSL_FINAL

INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,
TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,
CONTRA ,	ORDEN_OT ,	RUTAC ,	CODREQ ,	CZONAL, ZONAL ,	CMDF_NODO ,	INS_CODCLI ,
TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,
DESCRIPT ,	MOV ,	PLAYA ,	N_NEGOCIO ,	NEG_NUE ,	ACT_MAT ,	MOV_MAT ,	ACTIVIDAD ,	TELEFONO
,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,	IND_PAQ ,	CANT ,	COD_ACT, DIF
)
SELECT  (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),
(SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),
(SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),
(SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),
'BUCLE',	 'OPEX',	 'TDP',	 EECC,
CONTRATA,	 SUBSTRING(COD_UNICO,4,7),	 '0',	 '0',	 ZONAL, ZONAL,	 MDF,	 'AVERIAS',
	 ' ',	 ' ',	 ' ',	 FECHA_LIQU,
DBO.TRIM(TI_LIQN)+DBO.TRIM(TI_LIQN_DE),	 'AVERIAS',	 '0',	 'BASICA',	 'AVERIAS STB',	 'BA',	 'AVERIAS',	 'AVERIAS STB',	 '0',
NULL, NULL,	 NULL,	 NULL,	 NULL,	 COD_UNICO,	 '1',	 DBO.TRIM(TI_LIQN)+DBO.TRIM(TI_LIQN_DE), 'AVERIAS STB'
FROM STB_FINAL

ALTER TABLE DATA1908 ALTER COLUMN ORDEN_OT NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN INS_CODCLI NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN ANTENA NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN RUTAC NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN ARMARIO NVARCHAR(255)
ALTER TABLE DATA1908 ALTER COLUMN INSOURCING NVARCHAR(255)


INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,	TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,	CONTRA ,	ORDEN_OT ,	RUTAC ,	CODREQ ,
CZONAL, ZONAL ,	CMDF_NODO ,	MOV_MAT ,	INS_CODCLI ,	TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,	DESCRIPT ,	MOV ,	PLAYA ,	N_NEGOCIO ,	NEG_NUE ,
ACT_MAT ,	--MOV_MAT ,
ACTIVIDAD ,	TELEFONO ,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,	IND_PAQ ,	CANT ,	COD_ACT
)
SELECT  (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),	 'BUCLE',	 'OPEX',	 'TDP',	 CONTRA_TEC
,	 CONTRATA,	 SUBSTRING(CO_UNICO,4,7),	 0,	 0,	 ZON, ZON,	 CMDF,	 'AVERIAS',	 0,	 ' ',	 ' ',	 ' ',	 FE_LIQU
,	 DBO.TRIM(TI_LIQN)+DBO.TRIM(TI_LIQN_DE),	 'AVERIAS',	 0,	 'BASICA',	 'AVERIAS ADSL',	 'TB',	 --'AVERIAS',
'AVERIAS ADSL',
0,	 ' ',	 ' ',	 ' ',	 ' ',	 ' ',	 CO_UNICO,	 1,	 DBO.TRIM(TPEDIDO)
FROM INF_ADSL


INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,	TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,	CONTRA ,	ORDEN_OT ,
RUTAC ,	CODREQ ,	CZONAL, ZONAL ,	CMDF_NODO ,	--MOV_MAT
INS_CODCLI ,	TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,	DESCRIPT ,	MOV ,
PLAYA ,	N_NEGOCIO ,	NEG_NUE ,	ACT_MAT ,	MOV_MAT ,	ACTIVIDAD ,	TELEFONO ,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,
IND_PAQ ,	CANT ,	COD_ACT
)
SELECT (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),	 'BUCLE',	 'OPEX',	 'TDP',	 EECC
,	 CONTRATA,	 SUBSTRING(CO_UNICO,4,7),	 0,	 0,	 ZON, ZON,	 CMDF,	 --'AVERIAS'
0,	 ' ',	 ' ',	 ' ',	 FE_LIQU,
DBO.TRIM(TI_LIQN)+DBO.TRIM(TI_LIQN_DE),	 'AVERIAS',	 0,	 'BASICA',	 'AVERIAS STB',	 'TB',	 'AVERIAS',	 'AVERIAS STB',	 0,
' ',	 ' ',	 ' ',	 ' ',	 ' ',	 CO_UNICO,	 1,	 DBO.TRIM(TPEDIDO)
FROM INF_STB


INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,	TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,	CONTRA ,
ORDEN_OT ,	RUTAC ,	CODREQ ,
CZONAL, ZONAL ,	CMDF_NODO ,
INS_CODCLI ,	TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,	DESCRIPT ,	MOV ,	PLAYA ,	N_NEGOCIO ,	NEG_NUE ,	ACT_MAT ,	MOV_MAT ,	ACTIVIDAD ,
TELEFONO ,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,	IND_PAQ ,	CANT, DIF --,	COD_ACT
)
SELECT  (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),	 'BUCLE',	 'OPEX',	 'TDP',	 CONTRA_TEC
,	CONTRATA,
SUBSTRING(CODAVERIA,4,7),	 0,	 0,	 ZON, ZON,	 CO_MDF,
0,	 ' ',	 ' ',	 ' ',	 FE_LIQU,
DBO.TRIM(TI_LIQN)+DBO.TRIM(RE_TI_LIQN),	 'AVERIAS',	 0,	 'BASICA',	 'AVERIAS ADSL',	 'TB',	 'AVERIAS',	 'AVERIAS ADSL',
0,	 ' ',	 ' ',	 ' ',	 ' ',	 ' ',	 CODAVERIA,	 1, 'REITERADAS ADSL'--, DBO.TRIM(TIPOLINEA)
FROM REIT_ADSL

INSERT INTO data1908 (CECO ,	COD_CUENTA ,	AF ,	DESCTA ,	TIPO ,	DEFINICION ,	SOCIEDAD ,	CCONTR ,	CONTRA ,	ORDEN_OT ,	RUTAC ,	CODREQ ,
CZONAL, ZONAL ,	CMDF_NODO ,
INS_CODCLI ,	TIPREQ ,	CODMOTV ,	NROPLANO ,	FECEJE ,	DESCRIPT ,	MOV ,	PLAYA ,	N_NEGOCIO ,	NEG_NUE ,	ACT_MAT ,	MOV_MAT ,	ACTIVIDAD ,
TELEFONO ,	PREFIJO ,	CODSER ,	CODMOV ,	TSPEEDYACT ,	MODALACT ,	IND_PAQ ,	CANT , DIF--,	COD_ACT
)
SELECT  (SELECT CECO FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT COD_CUENTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT AF FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS')
,	 (SELECT DESCTA FROM CUENTA WHERE NEGOCIO = 'SPEEDY' AND MOV = 'AVERIAS'),	 'BUCLE',	 'OPEX',	 'TDP',	CONTRA_TEC
,	 CONTRATA,	 SUBSTRING(CODAVERIA,4,7),	 0,	 0,	 ZON, ZON,	 CO_MDF,
0,	 ' ',	 ' ',	 ' ',	 FE_LIQU,
DBO.TRIM(TI_LIQN)+DBO.TRIM(RE_TI_LIQN),	 'AVERIAS',	 0,	 'BASICA',	 'AVERIAS STB',	 'TB',	 'AVERIAS',	 'AVERIAS STB',	 0,
' ',	 ' ',	 ' ',	 ' ',	 ' ',	 CODAVERIA,	 1, 'REITERADAS STB'--,'	 DBO.TRIM(TIPOLINEA)
FROM REIT_STB


SELECT DIF, COUNT(*) FROM DATA1908 GROUP BY DIF
SELECT DIF, CONTRA, COUNT(*) FROM DATA1908 GROUP BY DIF, CONTRA HAVING CONTRA IS NULL

---------------------------------------------------------------------------------------------------------------------------------------
----- MONTO ADSL
SELECT DIF, SUM(MONTO) FROM (
SELECT DIF, PRECIO, BAR_UNI, PRECIO*BAR_UNI AS MONTO FROM DATA1908 WHERE DIF IN ('AVERIAS ADSL', 'AVERIAS STB') AND PRECIO IS NOT NULL AND DIF = 'AVERIAS ADSL') A
GROUP BY DIF


-- MONTO DE AVERIAS ADSL Y AVERIAS STB
SELECT DIF, SUM(MONTO) FROM (
SELECT DIF, PRECIO, BAR_UNI, CZONAL, PRECIO*BAR_UNI AS MONTO FROM DATA1908 WHERE DIF IN ('AVERIAS ADSL', 'AVERIAS STB') AND PRECIO IS NOT NULL) A
GROUP BY DIF



-- MONTO STB
SELECT DIF, SUM(MONTO) FROM (
SELECT DIF, PRECIO, BAR_UNI, PRECIO*BAR_UNI AS MONTO FROM DATA1908 WHERE DIF IN ('AVERIAS ADSL', 'AVERIAS STB') AND PRECIO IS NOT NULL AND DIF = 'AVERIAS STB') A
GROUP BY DIF

23698 / 768061

-- MONTOS POR CONTRATA Y POR AVERIA
SELECT CONTRA, DIF, ROUND(SUM(PRECIO*BAR_UNI),2) FROM DATA1908 GROUP BY CONTRA, DIF HAVING CONTRA IS NOT NULL

SELECT A.CONTRA, A.ZONAL, A.PRECIO, B.PRECIO FROM PRECIOS A JOIN PRECIO_NUEVO B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL

SELECT * FROM PRECIO_NUEVO
SELECT * FROM PRECIOS

23698 / 646511
---------------------------------------------------------------------------------------------------
--PRECIO VACIO PORQUE NO TIENEN CONTRA, Y NO TIENEN CONTRA PORQUE EL CODIGO DEL TECNICO NO TIENE LOS 2 PRIMEROS CARACTERES
SELECT DIF, ZONAL, CONTRA, PRECIO FROM DATA1908 WHERE PRECIO IS NULL
SELECT ZON FROM ADSL_FINAL

SELECT DIF, PRECIO, CZONAL, COUNT(*) FROM DATA1908 GROUP BY DIF, PRECIO, CZONAL
HAVING PRECIO IS NULL

SELECT DIF, BAR_UNI, PRECIO, ROUND(PRECIO*BAR_UNI,2) FROM DATA1908 WHERE DIF = 'AVERIAS ADSL'
SELECT DIF, BAR_UNI, PRECIO, ROUND(PRECIO*BAR_UNI,2) FROM DATA1908 WHERE DIF = 'AVERIAS STB'
SELECT DIF, BAR_UNI, PRECIO, ROUND(PRECIO*BAR_UNI,2) FROM DATA1908 WHERE DIF = 'REITERADAS ADSL'
SELECT DIF, BAR_UNI, PRECIO, ROUND(PRECIO*BAR_UNI,2) FROM DATA1908 WHERE DIF = 'REITERADAS STB'


SELECT DISTINCT DIF FROM DATA1908

SELECT CONTRA, DIF, ROUND(SUM(PRECIO*BAR_UNI),2) FROM DATA1908 GROUP BY CONTRA, DIF HAVING CONTRA IS NOT NULL


--******************************************************************************************
--******************************************************************************************
--******************************************************************************************

UPDATE DATA1908
SET COD_UNI = '72310-0'
WHERE DIF = 'AVERIAS ADSL'

UPDATE DATA1908
SET COD_UNI = '72310-0'
WHERE DIF = 'REITERADAS ADSL'

UPDATE DATA1908
SET COD_UNI = '72300-2'
WHERE DIF = 'AVERIAS STB'

UPDATE DATA1908
SET COD_UNI = '72300-2'
WHERE DIF = 'REITERADAS STB'


--***ADSL_FINAL**************************************************************************************
-- UNIDADES

UPDATE A
SET A.DESC_UNI = B.DESC_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0'


-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
-- PRECIOS

UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO,
A.OPEX = A.BAR_TOT*A.PRECIO
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'AVERIAS ADSL'

GO

-- JEFATURAS_REGIONES

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
--***********************************************************************************************************



--***STB_FINAL**************************************************************************************
UPDATE A
SET A.DESC_UNI = B.DESC_UNI,
	A.COD_UNI = B.COD_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72300-2'

GO

-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE

UPDATE A
SET A.PRECIO = B.PRECIO,
	A.MONTO = A.BAR_TOT*A.PRECIO,
	A.OPEX = A.BAR_TOT*A.PRECIO
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'AVERIAS STB'

GO

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF

--**************************************************************************************************


--***INF_ADSL***************************************************************************************

--**************************************************************************************************


--***INF_STB**************************************************************************************

--************************************************************************************************



--***REIT_ADSL**************************************************************************************
--UNIDADES

UPDATE A
SET A.COD_UNI = B.COD_UNI,
	A.DESC_UNI = 'REITERADA -75%',
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72310-0' AND DIF = 'REITERADAS ADSL'

-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
-- REIT_ADSL

UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'REITERADAS ADSL'


UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF
--************************************************************************************************


--***REIT_STB**************************************************************************************
-- REIT_STB
-- UNIDADES

UPDATE A
SET A.DESC_UNI = 'REITERADA -75%',
	A.COD_UNI = B.COD_UNI,
    A.BAR_UNI = B.BAR_UNI,
    A.BAR_TOT = B.BAR_UNI
FROM data1908 A JOIN UNIDADES B ON A.COD_UNI = B.COD_UNI
WHERE B.COD_UNI = '72300-2' AND DIF = 'REITERADAS STB'

-- CUANDO EN EL SEEK SEA UNA COLUMNA O MAS UTILIZAR UN UPDATE-JOIN SIN WHERE
--PRECIOS

UPDATE A
SET A.PRECIO = B.PRECIO,
A.MONTO = A.BAR_TOT*A.PRECIO*-.75,
A.OPEX = A.BAR_TOT*A.PRECIO*-.75
FROM data1908 A JOIN PRECIOS B ON A.CONTRA = B.CONTRA AND A.ZONAL = B.ZONAL
WHERE DIF = 'REITERADAS STB'

--JEFATURAS_REGIONES

UPDATE A
SET A.CZONAL = B.CZONAL,
	A.JEFATURA = B.JEF_CMR,
	A.ZONAL_BONO = B.ZONAL_BONO,
	A.JEFA_MAT = B.JEFA_MAT
FROM data1908 A JOIN JEFATURAS_REGIONES B ON A.CMDF_NODO = B.MDF AND A.ZONAL = B.ZONAL
--************************************************************************************************
