
------ CARGA AVERIAS A DATA -----------------------------------------------------------------------------------------------------
--********************************************************************************************************************************
-- BORRAR AVERIAS HFC, DTH Y GPON
DELETE FROM data1908
WHERE NEG_NUE IN ('AVERIAS HFC', 'AVERIAS DTH', 'AVERIAS GPON')

GO

-- ACTUALIZAR DE EZENTIS A CALATEL
UPDATE INDICA_PAIS
SET CONTRA = 'CALATEL'
WHERE DBO.TRIM(CONTRA) = 'EZENTIS';

GO


-- CREACION DE AVE

SELECT * INTO AVE_TABLA FROM (
SELECT * FROM INDICA_PAIS WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH' AND INF_CERT = 0 AND REITCERT30 = 0 AND SUBSTRING(DBO.TRIM(APAGAR),1,8) = 'RED CLIE'
UNION
SELECT * FROM INDICA_PAIS WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON' AND INF_CERT = 0 AND REITCERT30 = 0 AND SUBSTRING(DBO.TRIM(APAGAR),1,8) = 'RED CLIE'
UNION
SELECT * FROM INDICA_PAIS WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,5) = 'MOVIS' AND SUBSTRING(DBO.TRIM(APAGAR),1,8) = 'RED CLIE'
) A

GO

-- APPEND BLANK = INSERT INTO---------------------------------------
-- REPLACE

-- CREAMOS COLUMNAS EN LA MISMA AVE_TABLA, HACEMOS LOS UPDATES EN AVE_TABLA, LUEGO SE INSERTARA LAS COLUMNAS CREADAS Y UPDATEADAS A LA TABLA DATA1908
ALTER TABLE AVE_TABLA ADD N_NEGOCIO NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD NEG_NUE NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD ACT_MAT NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD ACTIVIDAD NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD NEGO_BONO NVARCHAR(255)

GO

UPDATE AVE_TABLA
SET N_NEGOCIO = 'DTH',
	NEG_NUE = 'AVERIAS DTH',
	ACT_MAT = 'DTH',
	ACTIVIDAD = 'AVERIAS DTH'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH'

GO

UPDATE AVE_TABLA
SET
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH'

GO
---------------------------------------------------------

UPDATE AVE_TABLA
SET N_NEGOCIO = 'GPON'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON'

GO

UPDATE AVE_TABLA
SET NEG_NUE = 'AVERIAS GPON'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON'

GO

UPDATE AVE_TABLA
SET ACT_MAT = 'GPON'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON'

GO

UPDATE AVE_TABLA
SET ACTIVIDAD = 'AVERIAS GPON'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON'

GO

UPDATE AVE_TABLA
SET NEGO_BONO = 'AVERIAS GPON'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON'

GO
----------------------------------------------------

UPDATE AVE_TABLA
SET N_NEGOCIO = 'MOVISTAR'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,8) = 'MOVISTAR'

GO

UPDATE AVE_TABLA
SET NEG_NUE = 'AVERIAS HFC'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,8) = 'MOVISTAR'

GO

UPDATE AVE_TABLA
SET ACT_MAT = 'HFC'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,8) = 'MOVISTAR'

GO

UPDATE AVE_TABLA
SET ACTIVIDAD = 'AVERIAS HFC'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,8) = 'MOVISTAR'

GO

UPDATE AVE_TABLA
SET NEGO_BONO = 'AVERIAS HFC'
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,8) = 'MOVISTAR'

GO

-- LINEA 111 A 124-----------
UPDATE DATA1908
SET TELEFONO = 0, PREFIJO = NULL, CODSER = NULL, CODMOV = NULL, TSPEEDYACT = NULL, MODALACT =  NULL, CANT = 1

GO


ALTER TABLE AVE_TABLA ADD COD_NUE NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD DESC_UNI NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD MONTO INT
ALTER TABLE AVE_TABLA ADD COD_NUE NVARCHAR(255)
ALTER TABLE AVE_TABLA ADD OPEX_NUE INT

GO

UPDATE AVE_TABLA
SET COD_NUE = '7708-8'
WHERE SERVICIO = 'MOVISTAR1'

GO

UPDATE AVE_TABLA
SET DESC_UNI = 'REITERADA AL 25%',
	MONTO = ROUND(MONTO*.25,2),
	DESC_NUE = 'REITERADA AL 25%',
	OPEX_NUE = ROUND(MONTO_NUE*.25,2)
WHERE REITCERT30 = 1 AND SERVICIO = 'MOVISTAR1'

GO

UPDATE AVE_TABLA
SET DESC_UNI = 'INFANCIA AL 25%',
	MONTO = ROUND(MONTO*.25,2),
	DESC_NUE = 'INFANCIA AL 25%',
	OPEX_NUE = ROUND(MONTO*.25,2)
WHERE REITCERT30 = 0 AND SERVICIO = 'MOVISTAR1' AND INF_CERT = 1

GO



UPDATE AVE_TABLA
SET DESC_UNI = DESC_UNI,
	 MONTO = MONTO,
	DESC_NUE =  DESC_NUE,
	OPEX_NUE = OPEX_NUE
WHERE REITCERT30 = 0 AND INF_CERT = 0 AND SERVICIO = 'MOVISTAR1'

GO

UPDATE AVE_TABLA
SET OPEX_NUE = (SELECT DISTINCT MONTO_NUE FROM AVE_TABLA WHERE SERVICIO <> 'MOVISTAR1' AND SERVICIO LIKE '%DTH%'),
	DESC_NUE = (SELECT DISTINCT DESC_NUE FROM AVE_TABLA WHERE SERVICIO <> 'MOVISTAR1' AND SERVICIO LIKE '%DTH%')
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH' AND SERVICIO <> 'MOVISTAR1'

GO

/*
IF EXISTS (SELECT SERVICIO FROM AVE_VW WHERE SERVICIO <> 'MOVISTAR1')
	IF EXISTS (SELECT * FROM AVE_VW WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH')
		UPDATE DATA1908
		SET DESC_NUE = (SELECT DISTINCT DESC_NUE FROM AVE_VW WHERE SERVICIO <> 'MOVISTAR1' AND SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH')
			--OPEX_NUE = (SELECT OPEX_NUE FROM AVE_VW WHERE SERVICIO <> 'MOVISTAR1' AND SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH')
*/
		-------------------------------------------------------------
-- **************************************** CERO COLUMNAS AFECTADAS REVISAR!!!! -****************************************
UPDATE AVE_TABLA
SET DESC_UNI = 'REITERADA',
	MONTO = (SELECT DISTINCT DESC_NUE FROM AVE_TABLA WHERE SERVICIO <> 'MOVISTAR1' AND SERVICIO LIKE '%DTH%' AND REITCERT30 = 1)
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH' AND SERVICIO <> 'MOVISTAR1' AND REITCERT30 = 1

GO


/*
		IF EXISTS (SELECT REITCERT30 FROM AVE_VW WHERE REITCERT30 = 1)
			UPDATE DATA1908
			SET DESC_UNI = 'REITERADA',
			MONTO = (SELECT ROUND(MONTO_NUE*.25,2) FROM AVE_VW WHERE SERVICIO LIKE '%DTH%' AND SERVICIO <> 'MOVISTAR' AND REITCERT30 = 1)
*/

--************************************************ CERO COLUMNAS AFECTADAS REVISAR!!!! --*****************************************************
UPDATE AVE_TABLA
SET DESC_UNI = 'INFANCIA',
	MONTO = (SELECT DISTINCT ROUND(MONTO_NUE*.25,2) FROM AVE_TABLA WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH' AND SERVICIO <> 'MOVISTAR1' AND REITCERT30 = 0 AND INF_CERT = 1)
WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) = 'DTH' AND SERVICIO <> 'MOVISTAR1' AND REITCERT30 = 0 AND INF_CERT = 1

GO

-- CODIGO NNECESARIO | SIRVE COMO GUIA | LINEA 165-166 DE CARGA_AVERIAS_A_DATA.PRG
UPDATE AVE_TABLA
SET DESC_UNI = DESC_UNI,
	MONTO = MONTO
WHERE SERVICIO LIKE '%DTH%' AND SERVICIO <> 'MOVISTAR1' AND REITCERT30 = 0 AND INF_CERT = 0

GO

UPDATE AVE_TABLA
SET DESC_UNI= DESC_UNI,
	MONTO = MONTO,
	OPEX_NUE = OPEX_NUE,
	DESC_NUE = DESC_NUE
WHERE SERVICIO <> 'MOVISTAR1' AND SERVICIO NOT LIKE '%DTH%' AND SERVICIO LIKE '%GPON%'

GO

/*
 IF EXISTS (SELECT SERVICIO FROM AVE_VW WHERE SERVICIO <> 'MOVISTAR1')
	IF EXISTS (SELECT * FROM AVE_VW WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,3) <> 'DTH')
		IF EXISTS (SELECT * FROM AVE_VW WHERE SUBSTRING(DBO.TRIM(SERVICIO),1,4) = 'GPON')
			UPDATE DATA1908
			SET DESC_UNI = (SELECT DESC_UNI FROM AVE_VW),
				MONTO = (SELECT MONTO FROM AVE_VW),
				OPEX_NUE = (SELECT MONTO_NUE FROM AVE_VW),
				DESC_NUE = (SELECT DESC_NUE FROM AVE_VW)
*/

-- INSERTAR FILAS DE LA TABLA AVE A LA TABLA DATA1 (DATA1908)
-- SE CORRE CUANDO AVE_TABLA ESTA ACTUALIZADO
INSERT INTO data1908 (CECO ,	    COD_CUENTA ,	    AF ,	    DESCTA ,	    TIPO ,	    DEFINICION ,	    SOCIEDAD ,	    CCONTR ,	    CONTRA ,	    ORDEN_OT ,	    RUTAC ,	    CODREQ ,	    CZONAL ,	    CMDF_NODO ,	    MOV_MAT ,	    INS_CODCLI ,	    TIPREQ ,	    CODMOTV ,	    NROPLANO ,	    FECEJE ,	    DESCRIPT ,	    MOV ,	    PLAYA ,	    telefono ,	    prefijo   ,	    codser    ,	    codmov    ,	    tspeedyact  ,	    modalact ,	    cant    ,	    cod_act ,	    cod_uni ,	    bar_uni_n ,	    pbar_nue  ,	    precio_nue, OPEX_NUE, BAR_UNI,BAR_TOT, PRECIO
)
SELECT  CECO,	 COD_CUENTA,	 AF,	 DESCTA,	 'BUCLE',	 'OPEX',	 'TMM',	 CODCTR,	 CONTRA,	 NROOT,	 RUTAC,	 CODREQ,	 CZONAL,	 CODNOD,	 'AVERIAS',	 CODCLI,	 TIPREQ,	 MOTGEN,	 PLANO,	 FECLIQ,	 DBO.TRIM(LIQ_DET)+' '+DBO.TRIM(COD_DET)+'-'+DBO.TRIM(COD_DES),	 'AVERIAS',	 OPE_PLAYAS,	 0,	 ' ',	 ' ',	 ' ',	 '  ',	 '  ',	 1,	 DBO.TRIM(tipreq)+DBO.TRIM(motgen),	 cod_uni,	 pbar_nue,	 pbar_nue,	 precio_nue,	 monto_nue, BAR_TOT, BAR_TOT, PRECIO
FROM AVE_TABLA

GO

UPDATE A
SET A.CZONAL = C.czonal,
	A.JEFATURA = C.jef_cmr,
	A.JEFA_MAT = C.jefa_mat
FROM data1908 A JOIN AVE_TABLA B ON A.CMDF_NODO = B.codnod JOIN jefaturas_regiones C ON B.CODNOD = C.MDF

GO

UPDATE A
SET A.ZONAL_BONO = C.zonal_bono
FROM data1908 A JOIN AVE_TABLA B ON A.CMDF_NODO = B.codnod JOIN jefaturas_regiones C ON B.CODNOD = C.MDF
WHERE SERVICIO LIKE '%MOVISTAR%'

GO
-- ************************************************************* LINEA 904

UPDATE A
SET A.ZONAL_BONO = C.zonal_bono
FROM data1908 A JOIN AVE_TABLA B ON A.CMDF_NODO = B.codnod JOIN jefaturas_regiones C ON B.CODNOD = C.MDF
WHERE C.jefa_mat = 'LIMA' AND A.CONTRA IS NULL

GO
